### PR TITLE
fix: ensure indicator bits can be toggled on -> off

### LINKED ISSUE #31: Confusing semantics of `PacketHeader::set_indicators`.
The name `set_indicators` is a bit confusing, as the behavior it implements is closer to "merge_indicators", because once a bit is set, it can't be unset.

Here's a test triggering the behavior:

```rust
#[test]
fn can_toggle_indicators() {
    use crate::prelude::*;
    let mut packet = Vrt::new_signal_data_packet();

    // Initially, trailer_included should be false
    assert!(matches!(packet.header().indicators(), Indicators::SignalData(si) if !si.trailer_included));

    // Turn on trailer_included
    packet.header_mut().set_indicators(Indicators::SignalData(SignalDataIndicators {
        trailer_included: true,
        ..Default::default()
    }));

    // Now, trailer_included should be true
    assert!(matches!(packet.header().indicators(), Indicators::SignalData(si) if si.trailer_included));

    // Turn trailer_included back off...
    packet.header_mut().set_indicators(Indicators::SignalData(SignalDataIndicators {
        trailer_included: false,
        ..Default::default()
    }));

    // Now, trailer_included should be false again
    assert!(matches!(packet.header().indicators(), Indicators::SignalData(si) if !si.trailer_included));
}
```

If this is intended behavior, I'd suggest documenting it more clearly or renaming the method. If this is _not_ the intended behavior, then you can see in the implementation that `|=` is used:

https://github.com/voyager-tech-inc/vita49-rs/blob/dbeb9fba6ea51bbfb10b42cbd5c88a7aacf3e02c/vita49/src/packet_header.rs#L340-L356

...and I think you want something like this instead:

```rust
...
self.hword_1 = (self.hword_1 & !(1 << 10)) | ((i.trailer_included as u16) << 10);
...
```

### PR DESCRIPTION
**Pull request by metasim**
Also:

* Refactored conversion to/from u16 & Indicators to simplify testing
* Added tests to ensure proper mapping between bits and flags
* Added test to ensure a set indicator can be turned off

Closes #31

---

## Bot Summary

This pull request refactors and improves the handling of indicator bits in the `PacketHeader` for the VITA 49 protocol implementation, making the code more maintainable and robust. The main changes include centralizing the encoding and decoding logic for indicator bits, updating the API for setting and retrieving indicators, and adding comprehensive tests to ensure correctness.

### Refactoring and Code Improvements

* Refactored indicator bit handling by moving the logic for encoding and decoding indicator fields into the `Indicators` enum itself, via new `as_u16` and `from_u16_for_packet` methods. This centralizes and simplifies bit manipulation, reducing code duplication and potential errors.
* Updated the `PacketHeader::indicators` and `set_indicators` methods to use the new centralized logic, improving clarity and ensuring consistent behavior.

### Testing Enhancements

* Added comprehensive unit tests for indicator bit handling, including toggling individual indicator fields and verifying correct encoding/decoding for all packet types. Introduced a macro to simplify assertions.
* Added missing import for `Indicators` in the test module to support new tests.

### Documentation

* Added a detailed table to the indicator bits documentation, clarifying the meaning of each bit for different packet types.

### Project Metadata

* Added "DataShapes AI, Inc." to the list of contributors in `AUTHORS.md`.

### CODE REVIEW

File: vita49/src/packet_header.rs [hunk 1]
```diff
@@ -124,6 +124,69 @@ pub enum Indicators {
...
+            }
+            PacketType::Command | PacketType::ExtensionCommand => {
+                Indicators::Command(CommandIndicators {
+                    ack_packet: i1,
+                    // i2 is reserved
+                    cancellation_packet: i3,
+                })
+            }
+        }
+    }
```
Comment (metasim) [inline vita49/src/packet_header.rs:194]: Moved conversion code from `PacketHeader` to `Indicators` for a) easier testing, and b) better coherence.

File: vita49/src/packet_header.rs [hunk 2]
```diff
@@ -306,53 +369,12 @@ impl PacketHeader {
...
-            }
-            Indicators::Context(i) => {
-                self.hword_1 |= (i.not_a_vita490_packet as u16) << 9;
-                self.hword_1 |= (i.timestamp_mode as u16) << 8;
-            }
-            Indicators::Command(i) => {
-                self.hword_1 |= (i.ack_packet as u16) << 10;
-                self.hword_1 |= (i.cancellation_packet as u16) << 8;
-            }
-        }
```
Comment (metasim) [inline vita49/src/packet_header.rs:355]: See: https://github.com/voyager-tech-inc/vita49-rs/pull/32/changes#r3149900693

File: vita49/src/packet_header.rs [hunk 3]
```diff
@@ -528,6 +550,7 @@ impl PacketHeader {
 
 #[cfg(test)]
 mod tests {
+    use crate::Indicators;
```
Comment (metasim) [inline vita49/src/packet_header.rs:560]: `Indicators` is not in `prelude`. Are imports here OK?

Comment (JohnMoon-Voyager) [reply vita49/src/packet_header.rs:560]: Yep, that's fine.

File: vita49/src/packet_header.rs [hunk 4]
```diff
@@ -306,53 +376,12 @@ impl PacketHeader {
...
-                self.hword_1 |= (i.not_a_vita490_packet as u16) << 9;
-                self.hword_1 |= (i.timestamp_mode as u16) << 8;
-            }
-            Indicators::Command(i) => {
-                self.hword_1 |= (i.ack_packet as u16) << 10;
-                self.hword_1 |= (i.cancellation_packet as u16) << 8;
-            }
-        }
+        let flags = indicators.as_u16();
+        self.hword_1 = self.hword_1 & !Indicators::MASK | flags;
```
[the remark this answers is not in the document]
Comment (JohnMoon-Voyager) [reply vita49/src/packet_header.rs]: I agree with at least the second suggestion for parentheses. I could go either way on the extra mask. Up to you.

Could you add the parens?

File: .gitignore [hunk 5]
```diff
@@ -5,3 +5,4 @@
 /target
 Cargo.lock
 *.vrt
+.idea
```
Comment (JohnMoon-Voyager) [inline .gitignore:8]: Nit: could you make this change its own commit?

**Review by JohnMoon-Voyager — CHANGES_REQUESTED** [review]
This looks really good! Just a couple of small things.

**Review by JohnMoon-Voyager — APPROVED** [review]
Thanks for the fix and detailed tests!
